global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'traefik-data'
    static_configs:
      - targets: ['traefik:8091']
