global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus-data'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'cadvisor-data'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'django-data'
    static_configs:
      - targets: ['django:8000']
  - job_name: 'rabbitmq-data'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'celery-data'
    static_configs:
      - targets: ['celery:5555']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']