services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      OTEL_SERVICE_NAME: django-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
    depends_on:
      - redis
      - otel-collector
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      environment:
      CELERY_BROKER_API_URL: http://guest:guest@rabbitmq:15672/api/
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      OTEL_SERVICE_NAME: celery-worker
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      DB_HOST: db
    ports:
      - '5555:5555'
    depends_on:
      - redis
      - otel-collector
      - db
    command: sh -c "sh start_celery_flower.sh"
    volumes:
      - ./backend:/app

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686" # 화면
      - "14268:14268" # http
      - "14250:14250" # grpc
      # - "4317:4317"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317" # grpc
      - "55681:55681" # http
    volumes:
      - ./opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]

volumes:
  postgres_data: